//✅

import { z } from "zod";
import i18n from '@/localization/i18n';


// Use a getter for the translation to ensure it's always the current language
const t = (key: string) => i18n.t(key);

export type DeviceApplicationT = {
  deviceId: number;
  serialNumber: string;
  model: string;
  packetType: string;
  suffix?: string | null;
  devicePhoneNumber: string;
  isConnectedVehicles: boolean;
  companyApplicationId?: string;
};



export const DeviceApplicationSchema = z.object({
  deviceId: z.number()
    .int()
    .positive({ error: () => t("validationErrors.invalidId") }),

  serialNumber: z.string()
    .min(1, { error: () => t("validationErrors.serialNumberRequired") }),

  model: z.string()
    .min(1, { error: () => t("validationErrors.modelRequired") }),

  packetType: z.string()
    .min(1, { error: () => t("validationErrors.packetTypeRequired") }),

  suffix: z.string().nullable().optional(),

  isConnectedVehicles: z.boolean().default(false),

  devicePhoneNumber: z.string()
    .length(11, { error: () => t("validationErrors.invalidPhoneNumber") }),

  companyApplicationId: z.string()

});

export type DeviceApplicationSchemaT = z.infer<typeof DeviceApplicationSchema>;



// export const DeviceApplicationSchema = z.object({
//   // Use .optional() if this schema is used for "Create" forms
//   // where the ID is generated by the database later.
//   deviceId: z.number().int().positive(),

//   serialNumber: z.string().min(1, "Serial number is required"),

//   model: z.string().min(1, "Model is required"),

//   // z.enum is cleaner for "STD" vs "ACC"
//   packetType: z.string().min(1, "Packet type is required"),


//   suffix: z.string().nullable().optional(),

//   isConnectedVehicles: z.boolean().default(false),

//   // Adding a regex or min length for phone numbers is good practice
//   devicePhoneNumber: z.string().min(11, "Invalid phone number"),

//   companyApplicationId: z.string()
// });

// // Extract the Type for use in your components
// export type DeviceApplicationSchemaT = z.infer<typeof DeviceApplicationSchema>;